name: Code Coverage

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Clear npm cache
        run: npm cache clean --force

      - name: delete node_modules clear dependency error
        run: rm -rf node_modules && rm -r package-lock.json

      - name: Setting global variables
        run: |
          export TEST_RPC_URL=http://192.168.1.44:9545/rpc/v0.5
          export TEST_RPC_URL=https://starknet-testnet.public.blastapi.io/rpc/v0.5
          export TEST_ACCOUNT_ADDRESS=0x065A822f0000000000000000000000000c26641
          export TEST_ACCOUNT_PRIVATE_KEY=0x02a80000000000000000000000001754438a

      - name: Install dependencies
        run: npm install

      - name: Setting global variables
        run: |
          export TEST_RPC_URL=http://192.168.1.44:9545/rpc/v0.5
          export TEST_RPC_URL=https://starknet-testnet.public.blastapi.io/rpc/v0.5
          export TEST_ACCOUNT_ADDRESS=0x065A822f0000000000000000000000000c26641
          export TEST_ACCOUNT_PRIVATE_KEY=0x02a80000000000000000000000001754438a

      - name: Run the tests
        run: npm test -- --coverage
